name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send a joke on slack
        uses: ./.github/adtions/slack-joke
        id: slack-joke 
        with:
          slack_username: kuanysh
          upload_joke: true
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Displaying joke output
        run: echo '${{ steps.slack-joke.outputs.joke }}''